### ISSUE TITLE
Strange probs and log probs computation for SAC critic loss

### ISSUE THREAD

**Issue by inspirit** [PyTorchRL/pytorchrl#15]
Hello
I was wondering why do you use following way to compute probs and log_probs for critic loss:
https://github.com/PyTorchRL/pytorchrl/blob/0ac3e2a9f83075974793ed5f3618c2fff7b45e1c/pytorchrl/agent/algorithms/sac.py#L392-L396

while for actor loss similar values computed in much simpler way:
https://github.com/PyTorchRL/pytorchrl/blob/0ac3e2a9f83075974793ed5f3618c2fff7b45e1c/pytorchrl/agent/algorithms/sac.py#L463-L466

is there any special reason for critic loss values?

**Comment by albertbou92** [comment]
Hello Inspirit,

There is no special reason. We initially wrote the code with the simpler code version. However, we found that in practice SAC discrete worked worse than other discrete algorithms. We rewrote the code with the more complex version just in case it was a numerical issue. However, in theory the calculations are the same.
