### ISSUE TITLE
Size mismatch for overlapping seq

### ISSUE THREAD

**Issue by inspirit** [PyTorchRL/pytorchrl#5]
https://github.com/PyTorchRL/pytorchrl/blob/19147505b16d0748e826815e12cf6d15af927f80/pytorchrl/agent/storages/off_policy/per_buffer.py#L207

Hello,
I have noticed there is size mismatch in above codes:
idxs size = sequence_length + overlap_length
errors size = non_overlap_length + overlap_length

so later when we try to broadcast here:
https://github.com/PyTorchRL/pytorchrl/blob/19147505b16d0748e826815e12cf6d15af927f80/pytorchrl/agent/storages/off_policy/per_buffer.py#L213

we got mismatch in sizes

**Comment by albertbou92** [comment]
Thank you very much for pointing it out. The issue is now solved. We corrected the sizes and now both errors and idxs match:

idxs size = non_overlap_length + overlap_length
errors size = non_overlap_length + overlap_length

version 1.3.61 included the fix
